language_code: ASL
language_name: American Sign Language

dataset:
  name: WLASL100
  raw_path: data/raw/ASL
  metadata_file: data/raw/ASL/nslt_100.json
  videos_path: data/raw/ASL/videos
  video_index: data/processed/ASL/WLASL100/wlasl100_video_index.csv
  processed_path: data/processed/ASL/WLASL100/keypoints
  label_map: data/label_maps/asl_wlasl100_labels.json

model:
  type: BiLSTM
  input_type: mediapipe_keypoints
  sequence_length: 60
  hidden_size: 256
  num_layers: 2
  dropout: 0.3
  num_classes: 100

training:
  batch_size: 32
  epochs: 40
  learning_rate: 0.001
  confidence_threshold: 0.60